### ISSUE TITLE
Silent failure on OS X

### ISSUE THREAD

**Issue by CGamesPlay** [fbehrens/sublime_ExternalREPL#2]
This is more of a note; something that might be useful in the README. When I press `Ctrl-Shift-Enter`, the cursor moves down a line but the tmux session gets no input.

The problem ended up being caused by `tmux` not being in Sublime's `PATH`. To verify that this, I opened the console `Ctrl-`` and ran:

``` python
from subprocess import check_output
check_output("which tmux", shell=True)
# subprocess.CalledProcessError: Command 'which tmux' returned non-zero exit status 1
check_output("echo $PATH", shell=True)
# b'/usr/bin:/bin:/usr/sbin:/sbin\n'
```

To fix this, I created a new file `~/Library/Application Support/Sublime Text 3/Packages/User/User.py`:

``` python
import os
os.environ['PATH'] = "/usr/local/bin:" + os.environ['PATH']
```

Sublime reloaded the plugin automatically and my `PATH` was correctly set up.

The reason this happened: I installed `tmux` using `brew install tmux`, which places it into `/usr/local/bin/tmux`. This is fine, because `/etc/paths` contains `/usr/local/bin`. However, `/etc/paths` is only used in console applications, so Sublime Text is exempted.

**Comment by fbehrens** [comment]
Thanks for the comment. I really appreciate your feedback. Sorry for the delay.
Yes configuration is a hazzle, I added a comment in the readme.
